server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      path: /api
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB
  cache:
    type: simple
  datasource: # 主数据源, todo:读写分离、按企业分库 https://blog.csdn.net/u011493599/article/details/53930394
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: master
    url: ${db.master.url}
    username: ${db.master.username}
    password: ${db.master.password}
    maxActive: ${db.maxActive}
    initialSize: ${db.initialSize}
    maxWait: ${db.maxWait}
    minIdle: ${db.minIdle}
    timeBetweenEvictionRunsMillis: ${db.timeBetweenEvictionRunsMillis}
    minEvictableIdleTimeMillis: ${db.minEvictableIdleTimeMillis}
    maxOpenPreparedStatements: ${db.maxOpenPreparedStatements}
    filters: stat,wall,logback
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zy.**.entity

springfox:
  documentation:
    swagger:
      v2:
        path: /docs

